test_factorial (__main__.TestExercice) ... ok
test_prefixes (__main__.TestExercice) ... ok
test_summation (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_summation (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 33, in test_summation
    output = exercice.prime_integer_summation()
  File "/home/runner/work/c03_ch5_exercices-mymanat/c03_ch5_exercices-mymanat/exercice.py", line 24, in prime_integer_summation
    while premier<=100:
UnboundLocalError: local variable 'premier' referenced before assignment

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=1)
